### ISSUE TITLE
Default action keyword being typed causes Flow Launcher to crash the plugin

### ISSUE THREAD

**Issue by ALLSTAR4** [KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher#31] opened 2023-10-13 23:52 UTC
Got this error everytime I type the default action keyword gl

Flow Launcher version: 1.16.2
OS Version: 22621.2428
IntPtr Length: 8
x64: True

Python Path: C:\Python312\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 10/14/2023 01:49:41
Exception:
System.ArgumentException: Must create DependencySource on same Thread as the DependencyObject.
   at System.Windows.DependencyObject.ValidateSources(DependencyObject d, DependencySource[] newSources, Expression expr)
   at System.Windows.Expression.ChangeSources(DependencyObject d, DependencyProperty dp, DependencySource[] newSources)
   at System.Windows.Data.BindingExpressionBase.ChangeSources(WeakDependencySource[] newSources)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.AttachDataItem()
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.TreeWalkHelper.OnInheritablePropertyChanged(DependencyObject d, InheritablePropertyChangeInfo info, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   at System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   at System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   at System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   at System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   at System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   at System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   at System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by KrystianLesniak** [comment] 2023-10-14 09:54
Hello. Thanks for contribution!
I will investigate this issue and let you know.

**Comment by KrystianLesniak** [comment] 2023-10-14 10:27
After investigation it is very hard for me to catch where the issue lies as the stack trace comes from some internal or Flow Launcher side, not from plugin code. I think I would need some help from you to find where the problem lies.

Can you please go into plugin settings and disable libraries synchronization one by one and check if the problem is gone after disabling one? And if so, please let me know which library might be causing this problem and which games you have installed for that library. 

Thanks in advance!

**Comment by ALLSTAR4** [comment] 2023-10-16 14:23
> @ALLSTAR4 After investigation it is very hard for me to catch where the issue lies as the stack trace comes from some internal or Flow Launcher side, not from plugin code. I think I would need some help from you to find where the problem lies.
> 
> Can you please go into plugin settings and disable libraries synchronization one by one and check if the problem is gone after disabling one? And if so, please let me know which library might be causing this problem and which games you have installed for that library.
> 
> Thanks in advance!

I disabled each library sync one by one and every single one gave the same error message. Sorry that I couldn't find the library that was the culprit.

**Comment by ALLSTAR4** [comment] 2023-10-16 14:35
> @ALLSTAR4 After investigation it is very hard for me to catch where the issue lies as the stack trace comes from some internal or Flow Launcher side, not from plugin code. I think I would need some help from you to find where the problem lies.
> 
> Can you please go into plugin settings and disable libraries synchronization one by one and check if the problem is gone after disabling one? And if so, please let me know which library might be causing this problem and which games you have installed for that library.
> 
> Thanks in advance!

It is the Xbox library sync causing issues and I only have Minecraft Launcher, Minecraft for Windows, Minecraft Preview for Windows and Minecraft Java installed via Xbox.

**Comment by KrystianLesniak** [comment] 2023-10-16 19:03
Thank you,, unfortunately I have not been able to reproduce the problem on my end, even with the same set of games...
It's a bit of wandering in the fog for me due to how not easy to navigate information this exception produces, but I have a clue where the problem may lie.
I've implemented a fix in version 1.4.5.

Can you please test if the problem still exists in this version?

If the update is still not available in the Flow Launcher Plugin Store, you can download it directly here (GamesLauncher.zip): https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/releases/tag/v1.4.5
and extract the contents of the zip file to: Start Flow Launcher -> Flow Launcher UserData Folder -> Plugins -> GamesLauncher-x.x.x

Please let me know if this version fixes your problem or not. If not, we will investigate further and thank you again for your help 😎

**Comment by ALLSTAR4** [comment] 2023-10-16 22:28
> @ALLSTAR4 Thank you,, unfortunately I have not been able to reproduce the problem on my end, even with the same set of games... It's a bit of wandering in the fog for me due to how not easy to navigate information this exception produces, but I have a clue where the problem may lie. I've implemented a fix in version 1.4.5.
> 
> Can you please test if the problem still exists in this version?
> 
> Update should be available soon in Flow Launcher Plugin Store but If the update is still not available and you want to check it sooner, you can download it directly here (GamesLauncher.zip): https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/releases/tag/v1.4.5 and extract the contents of the zip file to: Start Flow Launcher -> Flow Launcher UserData Folder -> Plugins -> GamesLauncher-x.x.x (Remember to exit flow launcher before copying)
> 
> Please let me know if this version fixes your problem or not. If not, we will investigate further and thank you again for your help 😎

Well I manually installed the plugin (as at the time the plugin was not yet updated in the plugin store) and the new version works like a charm 😁

**Comment by KrystianLesniak** [comment] 2023-10-17 06:31
Great to hear that! I am closing this issue then.

**Closed by KrystianLesniak** 2023-10-17 06:31 UTC
Labels: bug, help wanted
